apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dqknsdb3c-nodejs
  janus-idp.io/tekton: dqknsdb3c-nodejs
  backstage.io/kubernetes-id: dqknsdb3c-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dqknsdb3c-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
